{
 "title": "ZFS Pool Metrics (InfluxDB v2)",
 "description": "Dashboard of metrics generated by Richard Elling's cool \"zpool_influxdb\" utility (now included in OpenZFS), version for InfluxDB v2.",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "bucket", "query": "buckets()" },
   {
    "name": "hostname",
    "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"zpool_stats\")\n  |> keep(columns: [\"host\"])\n  |> unique(column: \"host\")\n  |> map(fn: (r) => ({_value: r[\"host\"]}))\n  |> yield(name: \"mean\")"
   },
   {
    "name": "poolname",
    "query": "  from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"zpool_stats\")\n  |> filter(fn: (r) => r[\"host\"] == \"${hostname}\")\n  |> keep(columns: [\"name\"])\n  |> unique(column: \"name\")\n  |> map(fn: (r) => ({_value: r[\"name\"]}))\n  |> yield(name: \"mean\")"
   },
   {
    "name": "ioparams",
    "label": "i/O Parameters",
    "query": "async_read, sync_read, scrub_read, async_write,  sync_write, trim_write"
   },
   { "name": "indagg", "label": "Individual / Aggregate", "query": "ind,agg" },
   {
    "name": "latencyparams",
    "label": "Latency Parameters",
    "query": "sync_read,async_read,scrub,disk_read,sync_write,async_write,trim,disk_write"
   },
   {
    "name": "TSCOLS",
    "label": "Time series columns to retain",
    "query": "[\"_field\"\\, \"_time\"\\, \"_value\"]"
   },
   {
    "name": "HMCOLS",
    "label": "Heatmap columns",
    "query": "[\"_time\"\\, \"_value\"\\, \"le\"]"
   },
   {
    "name": "NICEIFYLEG",
    "label": "Niceify Legend",
    "query": "(leg) => strings.title(v: strings.replaceAll(v:leg\\, t: \"_\"\\, u: \" \"))"
   }
  ]
 },
 "panels": [
  {
   "title": "Overview for $hostname $poolname",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Pool Activity ($poolname)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "zpool_stats",
     "query": "import \"strings\"\n\nKEEPCOLS = ${TSCOLS}\n\nniceify_legend = ${NICEIFYLEG} // function defined as variable- changes underscores to spaces + title-cases\n\nRawData = from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"zpool_stats\")\n  |> filter(fn: (r) => r[\"name\"] == \"${poolname}\")\n  |> filter(fn: (r) => r[\"host\"] == \"${hostname}\")\n  |> filter(fn: (r) => r[\"vdev\"] == \"root\")\n  |> filter(fn: (r) => r[\"_field\"] == \"read_bytes\" or r[\"_field\"] == \"write_bytes\" or r[\"_field\"] == \"read_ops\" or r[\"_field\"] == \"write_ops\")\n  |> derivative(nonNegative: true)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n\n  NamedData = RawData\n    |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:niceify_legend(leg: r[\"_field\"])}))\n    |> keep(columns: KEEPCOLS)\n    |> yield()",
     "select": [
      [
       { "params": [ "write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Write Bytes" ], "type": "alias" }
      ],
      [
       { "params": [ "read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Read Bytes" ], "type": "alias" }
      ],
      [
       { "params": [ "write_ops" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Write Ops" ], "type": "alias" }
      ],
      [
       { "params": [ "read_ops" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Read Ops" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$poolname$/" }
     ]
    }
   ]
  },
  {
   "title": "$poolname Pool Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_state",
     "groupBy": [
      { "params": [ "state" ], "type": "tag" },
      { "params": [ "state" ], "type": "tag" }
     ],
     "measurement": "zpool_stats",
     "query": "import \"strings\"\n\nKEEPCOLS = [\"_field\", \"_time\", \"_value\", \"state\"]\n\nniceify_legend = ${NICEIFYLEG} // function defined as variable- changes underscores to spaces + title-cases\n\nRawData = from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"zpool_stats\")\n  |> filter(fn: (r) => r[\"name\"] == \"${poolname}\")\n  |> filter(fn: (r) => r[\"host\"] == \"${hostname}\")\n  |> filter(fn: (r) => r[\"vdev\"] == \"root\")\n  |> filter(fn: (r) => r[\"_field\"] == \"size\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> last()\n\n  NamedData = RawData\n    //|> map(fn: (r) => ({_value:r._value, _time:r._time, _field:niceify_legend(leg: r[\"_field\"]), state: r[\"state\"]}))\n    |> map(fn: (r) => ({r: r._time, c: \"state\", v: r[\"state\"]}))\n    |> pivot(rowKey: [\"r\"], columnKey: [\"c\"], valueColumn: \"v\")\n    //|> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n    //|> keep(columns: KEEPCOLS)\n    |> yield(name: \"mean\")\n\n",
     "select": [
      [
       { "params": [ "size" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$poolname$/" }
     ]
    }
   ]
  },
  {
   "title": "vdev I/O Active Queues ($poolname)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "zpool_vdev_stats",
     "query": "import \"strings\"\n\nKEEPCOLS = ${TSCOLS}\n\nniceify_legend = ${NICEIFYLEG} // function defined as variable- changes underscores to spaces + title-cases\n\nRawData = from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"zpool_vdev_stats\")\n  |> filter(fn: (r) => r[\"name\"] == \"${poolname}\")\n  |> filter(fn: (r) => r[\"host\"] == \"${hostname}\")\n  |> filter(fn: (r) => r[\"vdev\"] == \"root\")\n  |> filter(fn: (r) => r[\"_field\"] == \"sync_w_active_queue\" or r[\"_field\"] == \"sync_r_active_queue\" or r[\"_field\"] == \"async_scrub_active_queue\" or r[\"_field\"] == \"async_w_active_queue\" or r[\"_field\"] == \"async_r_active_queue\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n\n  NamedData = RawData\n    |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:niceify_legend(leg: r[\"_field\"])}))\n    |> keep(columns: KEEPCOLS)\n    |> yield()",
     "select": [
      [
       { "params": [ "sync_w_active_queue" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Sync Write" ], "type": "alias" }
      ],
      [
       { "params": [ "sync_r_active_queue" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Sync Read" ], "type": "alias" }
      ],
      [
       { "params": [ "async_scrub_active_queue" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Async Scrub" ], "type": "alias" }
      ],
      [
       { "params": [ "async_w_active_queue" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Async Write" ], "type": "alias" }
      ],
      [
       { "params": [ "async_r_active_queue" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Async Read" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$poolname$/" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zpool_stats",
     "query": "// Note that we pull the overall pool size to weight vdev fragmentation\n//\n// eg vdev1 80GB  50%  (contributes 4/5)\n//    vdev2 20GB  10%  (contributes 1/5)\n//\n// → overall 50 * 4/5 + 10 * 1/5 = 42% weighted pool fragmentation \n//\n// see for more info: https://github.com/bertiebaggio/grafana-zfs-metrics/issues/2\n\nimport \"strings\"\n\nKEEPCOLS = ${TSCOLS}\n\nniceify_legend = ${NICEIFYLEG} // function defined as variable- changes underscores to spaces + title-cases\n\ndata = \n    from(bucket: \"${bucket}\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"name\"] == \"${poolname}\")\n    |> filter(fn: (r) => r[\"host\"] == \"${hostname}\")\n    |> filter(fn: (r) => r[\"_measurement\"] == \"zpool_stats\")\n    |> last()\n\nsizes =\n    data\n      |> filter(fn: (r) => r[\"_field\"] == \"size\")\n      |> filter(fn: (r) => not exists r[\"path\"]) // remove disks\n\n\n// create a table to extract a scalar)\npoolsizetable =\n    sizes\n      |> filter (fn: (r) => not strings.containsStr(v: r[\"vdev\"], substr: \"/\"))\n      |> map(fn: (r) => ({r with _field: \"size\", _field: \"pool_size\"}))\n      |> keep(columns: [\"_value\"])\n    \npoolsize = (poolsizetable |> findRecord(fn: (key) => true, idx:0))._value\n// jeez! https://github.com/influxdata/flux/issues/3522\n\nvdevs =\n    sizes\n      |> filter(fn: (r) => strings.containsStr(v: r[\"vdev\"], substr: \"/\"))\n      |> group(columns: [\"_time\", \"vdev\"])\n\nvdevwithpoolsize =\n    vdevs\n    |> set(key: \"zz_pool_size\", value: string(v: poolsize))\n    |> drop(columns: [\"_start\", \"_stop\"])\n\n\nfragmentation = \n   data\n      |> filter(fn: (r) => r[\"_field\"] == \"fragmentation\")\n\nfragnodisks = \n    fragmentation\n      |> filter(fn: (r) => not exists r[\"path\"])\n      |> keep(columns: [\"vdev\", \"_field\", \"_value\", \"_time\", \"_measurement\", \"host\", \"name\", \"state\"])\n      |> group(columns: [\"_time\"])\n\nvdevfrag =\n    fragnodisks\n      |> unique(column: \"vdev\")\n      |> filter(fn: (r) => strings.containsStr(v: r[\"vdev\"], substr: \"/\"))\n\nsizeandfrag =\n  join(tables: {f: vdevfrag, s: vdevwithpoolsize}, on: [\"vdev\", \"_time\"])\n  // https://github.com/EMCECS/influx/blob/master/query/docs/SPEC.md#join\n  |> keep(columns: [\"_time\", \"vdev\", \"zz_pool_size\", \"_value_f\", \"_value_s\"]) // _f = fragmention, _s = vdev size\n  |> group(columns: [\"_time\"])\n  \n\nweightedfragmentationbyvdev =\n  sizeandfrag // then rename fields\n  |> map(fn: (r) => ({\n      _time: r._time,\n      fragmentation: r._value_f,\n      size: r._value_s,\n      vdev: r.vdev,\n      pool_size: r.zz_pool_size,\n      ratio: float(v: r._value_s) / float(v: r.zz_pool_size),\n    })\n  )\n  |> map(fn: (r) => ({ \n        _time: r._time,\n        fragmentation: r.fragmentation,\n        vdev: r.vdev,\n        ratio: r.ratio,\n        weighted_fragmentation: float(v: r.fragmentation) * float(v: r.ratio),\n  }))\n  \n\npoolfragmentation = //finally!\n  weightedfragmentationbyvdev\n  |> sum(column: \"weighted_fragmentation\")\n  |> map(fn: (r) => ({\n      _time: r._time,\n      _field: \"fragmentation\",\n      _value: r.weighted_fragmentation,\n  }) )\n\n\nerrors = \n  data\n  |> filter(fn: (r) => r[\"_field\"] == \"read_errors\" or r[\"_field\"] == \"write_errors\" or r[\"_field\"] == \"checksum_errors\")\n  |> filter(fn: (r) => not exists r[\"path\"]) // drop disks\n  |> filter(fn: (r) => not strings.containsStr(v: r[\"vdev\"], substr: \"/\")) // only pool\n  |> keep(columns: [\"_field\", \"_time\", \"_value\"])\n  \n\nfraganderrors = \n  union(tables: [errors, poolfragmentation])\n  |> group(columns: [\"_field\"])\n\n  NamedData = fraganderrors\n    |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:niceify_legend(leg: r[\"_field\"])}))\n    |> keep(columns: KEEPCOLS)\n    |> yield()",
     "select": [
      [
       { "params": [ "read_errors" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Read Errors" ], "type": "alias" }
      ],
      [
       { "params": [ "write_errors" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Write Errors" ], "type": "alias" }
      ],
      [
       { "params": [ "fragmentation" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Fragmentation" ], "type": "alias" }
      ],
      [
       { "params": [ "checksum_errors" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Checksum Errors" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$poolname$/" },
      { "condition": "AND", "key": "vdev", "operator": "=", "value": "root" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zpool_stats",
     "query": "import \"strings\"\n\nKEEPCOLS = ${TSCOLS}\n\nniceify_legend = ${NICEIFYLEG} // function defined as variable- changes underscores to spaces + title-cases\n\nRawData = from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"zpool_stats\")\n  |> filter(fn: (r) => r[\"name\"] == \"${poolname}\")\n  |> filter(fn: (r) => r[\"host\"] == \"${hostname}\")\n  |> filter(fn: (r) => r[\"vdev\"] == \"root\")\n  |> filter(fn: (r) => r[\"_field\"] == \"alloc\" or r[\"_field\"] == \"free\" or r[\"_field\"] == \"size\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> last()\n\n  NamedData = RawData\n    |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:niceify_legend(leg: r[\"_field\"])}))\n    |> keep(columns: KEEPCOLS)\n    |> yield()",
     "select": [
      [
       { "params": [ "alloc" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Alloc" ], "type": "alias" }
      ],
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Free" ], "type": "alias" }
      ],
      [
       { "params": [ "size" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Size" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$poolname$/" },
      { "condition": "AND", "key": "vdev", "operator": "=", "value": "root" }
     ]
    }
   ]
  },
  {
   "title": "vdev I/O Pending Queues ($poolname)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "zpool_vdev_stats",
     "query": "import \"strings\"\n\nKEEPCOLS = ${TSCOLS}\n\nniceify_legend = ${NICEIFYLEG} // function defined as variable- changes underscores to spaces + title-cases\n\nRawData = from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"zpool_vdev_stats\")\n  |> filter(fn: (r) => r[\"name\"] == \"${poolname}\")\n  |> filter(fn: (r) => r[\"host\"] == \"${hostname}\")\n  |> filter(fn: (r) => r[\"vdev\"] == \"root\")\n  |> filter(fn: (r) => r[\"_field\"] == \"sync_w_pend_queue\" or r[\"_field\"] == \"sync_r_pend_queue\" or r[\"_field\"] == \"async_scrub_pend_queue\" or r[\"_field\"] == \"async_w_pend_queue\" or r[\"_field\"] == \"async_r_pend_queue\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n\n  NamedData = RawData\n    |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:niceify_legend(leg: r[\"_field\"])}))\n    |> keep(columns: KEEPCOLS)\n    |> yield()",
     "select": [
      [
       { "params": [ "sync_w_pend_queue" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Sync Write" ], "type": "alias" }
      ],
      [
       { "params": [ "sync_r_pend_queue" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Sync Read" ], "type": "alias" }
      ],
      [
       { "params": [ "async_scrub_pend_queue" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Async Scrub" ], "type": "alias" }
      ],
      [
       { "params": [ "async_w_pend_queue" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Async Write" ], "type": "alias" }
      ],
      [
       { "params": [ "async_r_pend_queue" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Async Read" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$poolname$/" }
     ]
    }
   ]
  },
  {
   "title": "Pool Usage ($poolname)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "zpool_stats",
     "query": "// Note that we pull the overall pool size to weight vdev fragmentation\n//\n// eg vdev1 80GB  50%  (contributes 4/5)\n//    vdev2 20GB  10%  (contributes 1/5)\n//\n// → overall 50 * 4/5 + 10 * 1/5 = 42% weighted pool fragmentation \n//\n// see for more info: https://github.com/bertiebaggio/grafana-zfs-metrics/issues/2\n\nimport \"strings\"\n\nKEEPCOLS = ${TSCOLS}\n\nniceify_legend = ${NICEIFYLEG} // function defined as variable- changes underscores to spaces + title-cases\n\ndata = \n    from(bucket: \"${bucket}\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"name\"] == \"${poolname}\")\n    |> filter(fn: (r) => r[\"host\"] == \"${hostname}\")\n    |> filter(fn: (r) => r[\"_field\"] == \"alloc\" or r[\"_field\"] == \"size\" or r[\"_field\"] == \"free\" or r[\"_field\"] == \"fragmentation\")\n\nsizes =\n    data\n      |> filter(fn: (r) => r[\"_field\"] == \"size\")\n      |> filter(fn: (r) => not exists r[\"path\"]) // remove disks\n\n// create a table to extract a scalar)\npoolsizetable =\n    sizes\n      |> filter (fn: (r) => not strings.containsStr(v: r[\"vdev\"], substr: \"/\"))\n      |> map(fn: (r) => ({r with _field: \"size\", _field: \"pool_size\"}))\n      |> keep(columns: [\"_value\"])\n    \npoolsize = (poolsizetable |> findRecord(fn: (key) => true, idx:0))._value\n// jeez! https://github.com/influxdata/flux/issues/3522\n\nvdevs =\n    sizes\n      |> filter(fn: (r) => strings.containsStr(v: r[\"vdev\"], substr: \"/\"))\n      |> group(columns: [\"_time\", \"vdev\"])\n\nvdevwithpoolsize =\n    vdevs\n    |> set(key: \"zz_pool_size\", value: string(v: poolsize))\n    |> drop(columns: [\"_start\", \"_stop\"])\n\nfragmentation = \n   data\n      |> filter(fn: (r) => r[\"_field\"] == \"fragmentation\")\n\nfragnodisks = \n    fragmentation\n      |> filter(fn: (r) => not exists r[\"path\"])\n      |> keep(columns: [\"vdev\", \"_field\", \"_value\", \"_time\", \"_measurement\", \"host\", \"name\", \"state\"])\n      |> group(columns: [\"_time\"])\n\nvdevfrag =\n    fragnodisks\n      |> unique(column: \"vdev\")\n      |> filter(fn: (r) => strings.containsStr(v: r[\"vdev\"], substr: \"/\"))\n\nsizeandfrag =\n  join(tables: {f: vdevfrag, s: vdevwithpoolsize}, on: [\"vdev\", \"_time\"])\n  // https://github.com/EMCECS/influx/blob/master/query/docs/SPEC.md#join\n  |> keep(columns: [\"_time\", \"vdev\", \"zz_pool_size\", \"_value_f\", \"_value_s\"]) // _f = fragmention, _s = vdev size\n  |> group(columns: [\"_time\"])\n\nweightedfragmentationbyvdev =\n  sizeandfrag // then rename fields\n  |> map(fn: (r) => ({\n      _time: r._time,\n      fragmentation: r._value_f,\n      size: r._value_s,\n      vdev: r.vdev,\n      pool_size: r.zz_pool_size,\n      ratio: float(v: r._value_s) / float(v: r.zz_pool_size),\n    })\n  )\n  |> map(fn: (r) => ({ \n        _time: r._time,\n        fragmentation: r.fragmentation,\n        vdev: r.vdev,\n        ratio: r.ratio,\n        weighted_fragmentation: float(v: r.fragmentation) * float(v: r.ratio),\n  }))\n\npoolfragmentation = //finally!\n  weightedfragmentationbyvdev\n  |> sum(column: \"weighted_fragmentation\")\n  |> map(fn: (r) => ({\n      _time: r._time,\n      _field: \"fragmentation\",\n      _value: r.weighted_fragmentation,\n  }) )\n  |> group(columns: [\"_field\"])\n\n\notherdata = \n  data\n  |> filter(fn: (r) => r[\"_field\"] != \"fragmentation\")\n  |> filter(fn: (r) => not exists r[\"path\"]) // drop disks\n  |> filter(fn: (r) => not strings.containsStr(v: r[\"vdev\"], substr: \"/\")) // only pool\n  |> keep(columns: [\"_field\", \"_time\", \"_value\"])\n\nfragandother = \n  union(tables: [otherdata, poolfragmentation])\n\nNamedData = fragandother\n  |> map(fn: (r) => ({_value:r._value, _time:r._time, _field:niceify_legend(leg: r[\"_field\"])}))\n  |> keep(columns: KEEPCOLS)\n  |> yield()",
     "select": [
      [
       { "params": [ "alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Allocated" ], "type": "alias" }
      ],
      [
       { "params": [ "size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Size" ], "type": "alias" }
      ],
      [
       { "params": [ "free" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Free" ], "type": "alias" }
      ],
      [
       { "params": [ "fragmentation" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Fragmentation" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$poolname$/" },
      { "condition": "AND", "key": "vdev", "operator": "=", "value": "root" }
     ]
    }
   ]
  },
  {
   "title": "Latencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Reads (rate)",
   "type": "heatmap",
   "description": "Latency histogram for the total reads of a ZFS pool",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 16 },
   "targets": [
    {
     "alias": "$tag_le",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "le" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zpool_latency",
     "query": "KEEPCOLS = ${HMCOLS}\n\nRawData = from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"zpool_latency\")\n  |> filter(fn: (r) => r[\"vdev\"] == \"root\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total_read\") |> derivative(nonNegative: true)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n\nNamedData = RawData\n  |> keep(columns: KEEPCOLS)\n  |> yield()",
     "select": [
      [
       { "params": [ "total_read" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$poolname$/" },
      { "condition": "AND", "key": "vdev", "operator": "=", "value": "root" }
     ]
    }
   ]
  },
  {
   "title": "Total Writes (rate)",
   "type": "heatmap",
   "description": "Latency histogram for the total writes of a ZFS pool",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 16 },
   "targets": [
    {
     "alias": "$tag_le",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "le" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zpool_latency",
     "query": "KEEPCOLS = ${HMCOLS}\n\nRawData = from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"zpool_latency\")\n  |> filter(fn: (r) => r[\"vdev\"] == \"root\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total_write\") |> derivative(nonNegative: true)\n  |> drop(columns: [\"_start\", \"_stop\", \"host\", \"name\", \"vdev\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n\nNamedData = RawData\n  |> keep(columns: KEEPCOLS)\n  |> yield()",
     "select": [
      [
       { "params": [ "total_write" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$poolname$/" },
      { "condition": "AND", "key": "vdev", "operator": "=", "value": "root" }
     ]
    }
   ]
  },
  {
   "title": "Queue $latencyparams Latency Rate",
   "type": "heatmap",
   "description": "Latency histogram for $latencyparams of pool $poolname",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "repeat": "latencyparams",
   "targets": [
    {
     "query": "KEEPCOLS = ${HMCOLS}\n\nRawData = from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"zpool_latency\")\n  |> filter(fn: (r) => r[\"host\"] == \"${hostname}\")\n  |> filter(fn: (r) => r[\"name\"] == \"${poolname}\")\n  |> filter(fn: (r) => r[\"vdev\"] == \"root\")\n  |> filter(fn: (r) => r[\"_field\"] == \"${latencyparams}\") |> derivative(nonNegative: true)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n\nNamedData = RawData\n  |> keep(columns: KEEPCOLS)\n  |> yield()"
    }
   ]
  },
  {
   "title": "I/O Sizes ($indagg)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "repeat": "indagg",
   "collapsed": true,
   "panels": [
    {
     "title": "ZFS IO - ${ioparams}_${indagg}",
     "type": "heatmap",
     "description": "$indagg I/O Sizes - $ioparams",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 41 },
     "repeat": "ioparams",
     "targets": [
      {
       "query": "KEEPCOLS = ${HMCOLS}\n\nRawData = from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"zpool_io_size\")\n  |> filter(fn: (r) => r[\"vdev\"] == \"root\")\n  |> filter(fn: (r) => r[\"_field\"] == \"${ioparams}_${indagg}\") |> derivative(nonNegative: true)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n\nNamedData = RawData\n  |> keep(columns: KEEPCOLS)\n  |> yield()"
      }
     ]
    }
   ]
  }
 ]
}